version: '3'

services:
  task:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=json-validation-service
    ports:
      - "8082:8082"
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/